# Generated by Django 2.2 on 2020-09-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fix', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=20)),
                ('order_type', models.CharField(max_length=20)),
                ('direction', models.CharField(max_length=20)),
                ('exec_date', models.DateTimeField()),
            ],
        ),
    ]
